Repository adaptlearning/adapt_framework, pull requests merged in 2018-02, with the labels that each got.

#1962 issue/1961: fixes css loading issues
  src/core/js/scriptLoader.js
Labels: bug, high priority

#1963 issue/1944: fixed build.min.js output and includes bug
  grunt/config/build-config.js
  grunt/helpers.js
  grunt/tasks/build-config.js
Labels: bug

#1834 Add attribute for _disableAccessibilityState
  src/core/js/views/componentView.js
  src/core/schema/component.model.schema
  src/core/templates/partials/state.hbs
Labels: accessibility

#1838 Use helper for aria-level attributes
  src/core/js/accessibility.js
  src/core/templates/article.hbs
  src/core/templates/block.hbs
  src/core/templates/page.hbs
  src/core/templates/partials/component.hbs
  src/course/config.json
Labels: accessibility

#1973 issue/1972: improved less compilation order
  grunt/config/less.js
  grunt/helpers.js
  grunt/tasks/less.js
  package.json
Labels: enhancement

#1971 issue/1966: minification fixes
  grunt/config/uglify.js
  src/core/js/views/notifyView.js
Labels: bug

#1948 issue/1727: improved screen reading
  src/core/js/accessibility.js
  src/core/js/helpers.js
  src/core/js/libraries/jquery.a11y.js
  src/core/less/base.less
Labels: accessibility

#1976 issue/1975: bug fix misnamed argument
  src/core/js/accessibility.js
Labels: bug

#1978 issue/1977: a11y: remove white-space tabbable regions
  src/core/js/libraries/jquery.a11y.js
Labels: bug

#1830 Move accessibility toggle and instructions from body to navigation
  src/core/js/accessibility.js
  src/core/js/views/accessibilityView.js
  src/core/js/views/navigationView.js
  src/core/less/base.less
  src/core/templates/navigation.hbs
  src/course/config.json
  src/index.html
Labels: accessibility
