Repository adaptlearning/adapt_framework, pull requests merged in 2020-05, with the labels that each got.

#2738 issue/2733 Fixed ES6-8 debugging
  grunt/config/babel.js
  package.json
Labels: bug

#2737 issue/2736 Added columns count warning and delimiter detection
  grunt/helpers/Translate.js
Labels: bug

#2735 Added template + partial render events and a fix for lazyloading images
  src/core/js/app.js
  src/core/js/fixes.js
  src/core/js/fixes/img.lazyload.js
  src/core/js/templateRenderEvent.js
  src/core/js/templates.js
  src/core/js/views/navigationView.js
  src/core/libraries/imageReady.js
  src/core/schema/config.model.schema
  src/course/config.json
Labels: bug

#2711 issue/2709 v5.5.0
  grunt/config/babel.js
  grunt/config/watch.js
  grunt/helpers/data/Language.js
  grunt/tasks/build.js
  grunt/tasks/dev.js
  grunt/tasks/diff.js
  grunt/tasks/language-data-manifests.js
  grunt/tasks/server-build.js
  src/core/js/a11y.js
  src/core/js/adapt.js
  src/core/js/app.js
  src/core/js/collections/adaptCollection.js
  src/core/js/collections/adaptSubsetCollection.js
  src/core/js/data.js
  src/core/js/headings.js
  src/core/js/logging.js
  src/core/js/models/adaptModel.js
  src/core/js/models/articleModel.js
  src/core/js/models/blockModel.js
  src/core/js/models/buildModel.js
  src/core/js/models/componentModel.js
  src/core/js/models/configModel.js
  src/core/js/models/contentObjectModel.js
  src/core/js/models/courseModel.js
  src/core/js/models/itemModel.js
  src/core/js/models/itemsComponentModel.js
  src/core/js/models/itemsQuestionModel.js
  src/core/js/models/lockingModel.js
  src/core/js/models/menuModel.js
  src/core/js/models/pageModel.js
  src/core/js/models/questionModel.js
  src/core/js/models/routerModel.js
  src/core/js/mpabc.js
  src/core/js/router.js
  src/core/js/scrolling.js
  src/core/js/views/adaptView.js
  src/core/js/views/articleView.js
  src/core/js/views/blockView.js
  src/core/js/views/buttonsView.js
  src/core/js/views/componentView.js
  src/core/js/views/contentObjectView.js
  src/core/js/views/headingView.js
  src/core/js/views/menuItemView.js
  src/core/js/views/menuView.js
  src/core/js/views/navigationView.js
  src/core/js/views/pageView.js
  src/core/js/views/questionView.js
  src/core/js/wait.js
Labels: enhancement, non-breaking

#2771 issue/2770 Corrected typo in contentObjectView remove events
  src/core/js/views/contentObjectView.js
Labels: bug

#2765 issue/2764 Added none helper and made any+all inline&blocks helpers
  src/core/js/helpers.js
Labels: enhancement, non-breaking

#2746 issue/2745 decontaminated toJSON functions
  src/core/js/models/adaptModel.js
  src/core/js/models/itemsComponentModel.js
  src/core/js/mpabc.js
Labels: bug, enhancement, non-breaking
