Repository adaptlearning/adapt_framework, pull requests merged in 2020-03, with the labels that each got.

#2652 issue/2647 Converted AdaptModel to ES Class
  src/core/js/models/adaptModel.js
  src/core/js/models/blockModel.js
Labels: enhancement, non-breaking

#2674 Converted child models of AdaptModel to ES6 Class
  src/core/js/data.js
  src/core/js/models/adaptModel.js
  src/core/js/models/articleModel.js
  src/core/js/models/blockModel.js
  src/core/js/models/componentModel.js
  src/core/js/models/contentObjectModel.js
  src/core/js/models/courseModel.js
  src/core/js/models/menuModel.js
  src/core/js/models/pageModel.js
Labels: enhancement

#2684 issue/2677 Exposed router controller at Adapt.router, converted to ES6
  src/core/js/router.js
Labels: enhancement

#2683 issue/2678 Added Adapt.log.removed and Adapt.log.deprecated
  src/core/js/a11y/log.js
  src/core/js/logging.js
  src/core/js/router.js
  src/core/schema/config.model.schema
  src/course/config.json
Labels: enhancement

#2667 issue/2662 Formalised plugin, data, schema and translate API
  grunt/config/build-config.js
  grunt/config/replace.js
  grunt/config/tracking-insert.js
  grunt/config/tracking-remove.js
  grunt/config/tracking-reset.js
  grunt/config/translate.js
  grunt/helpers.js
  grunt/helpers/Data.js
  grunt/helpers/Framework.js
  grunt/helpers/Plugins.js
  grunt/helpers/Schemas.js
  grunt/helpers/Translate.js
  grunt/helpers/data/Language.js
  grunt/helpers/data/LanguageFile.js
  grunt/helpers/lib/JSONFile.js
  grunt/helpers/lib/JSONFileItem.js
  grunt/helpers/plugins/Plugin.js
  grunt/helpers/schema/ExtensionSchema.js
  grunt/helpers/schema/GlobalsSchema.js
  grunt/helpers/schema/ModelSchema.js
  grunt/helpers/schema/ModelSchemas.js
  grunt/helpers/schema/Schema.js
  grunt/tasks/build-config.js
  grunt/tasks/check-json.js
  grunt/tasks/handlebars.js
  grunt/tasks/schema-defaults.js
  grunt/tasks/tracking-insert.js
  grunt/tasks/tracking-remove.js
  grunt/tasks/tracking-reset.js
  grunt/tasks/translate.js
  grunt/tasks/translate/createLookupTable.js
  grunt/tasks/translate/exportFile.js
  grunt/tasks/translate/extractCourseData.js
  grunt/tasks/translate/helper.js
  grunt/tasks/translate/loadCourseData.js
  grunt/tasks/translate/loadLanguageFiles.js
  grunt/tasks/translate/loadMasterCourse.js
  grunt/tasks/translate/loadTranslateConfig.js
  grunt/tasks/translate/parseSchema.js
  grunt/tasks/translate/saveCourseData.js
  grunt/tasks/translate/updateCourseData.js
  package.json
Labels: enhancement, non-breaking

#2644 issue/2363 drop src/course pathway in grunt
  .gitignore
  build/course/config.json
  build/course/en/articles.json
  build/course/en/blocks.json
  build/course/en/components.json
  build/course/en/contentObjects.json
  build/course/en/course.json
  build/course/en/images/accordion-full.png
  build/course/en/images/full-width.png
  build/course/en/images/gmcq.png
  build/course/en/images/hotgraphic.png
  build/course/en/images/menu-item.png
  build/course/en/images/narrative.png
  build/course/en/images/single-width.png
  build/course/en/images/vanilla-swatch.jpg
  build/course/en/video/c-40.jpg
  build/course/en/video/c-40.mp4
  build/course/en/video/c-40.vtt
  grunt/config/clean.js
  grunt/config/copy.js
  grunt/config/json-prettify.js
  grunt/config/jsonlint.js
  grunt/config/watch.js
  grunt/helpers.js
  grunt/tasks/build.js
  grunt/tasks/check-json.js
  grunt/tasks/create-json-config.js
  grunt/tasks/dev.js
  grunt/tasks/diff.js
  grunt/tasks/json-prettify.js
  grunt/tasks/minify.js
  grunt/tasks/schema-defaults.js
  grunt/tasks/server-build.js
  grunt/tasks/tracking-insert.js
  grunt/tasks/tracking-remove.js
  grunt/tasks/tracking-reset.js
  grunt/tasks/translate/exportFile.js
  grunt/tasks/translate/loadCourseData.js
  grunt/tasks/translate/loadMasterCourse.js
  grunt/tasks/translate/saveCourseData.js
  src/course/config.json
  src/course/en/articles.json
  src/course/en/blocks.json
  src/course/en/components.json
  src/course/en/contentObjects.json
  src/course/en/course.json
Labels: breaking, enhancement

#2648 issue/2647 add es6-8 support
  grunt/config/babel.js
  grunt/config/clean.js
  grunt/config/javascript.js
  grunt/config/watch.js
  grunt/helpers.js
  grunt/tasks/build.js
  grunt/tasks/dev.js
  grunt/tasks/diff.js
  grunt/tasks/server-build.js
  package.json
  src/core/js/a11y/log.js
  src/core/js/data.js
  src/core/js/logging.js
  src/core/js/models/adaptModel.js
  src/core/js/models/articleModel.js
  src/core/js/models/blockModel.js
  src/core/js/models/componentModel.js
  src/core/js/models/contentObjectModel.js
  src/core/js/models/courseModel.js
  src/core/js/models/menuModel.js
  src/core/js/models/pageModel.js
  src/core/js/router.js
  src/core/libraries/backbone.controller.js
  src/core/libraries/backbone.min.js
  src/core/libraries/polyfill.min.js
  src/core/libraries/promise-polyfill.min.js
  src/core/required/adapt/js/scriptLoader.js
  src/core/schema/config.model.schema
  src/course/config.json
Labels: enhancement, non-breaking

#2700 issue/2669 Converted AdaptView to ES6
  src/core/js/views/adaptView.js
Labels: enhancement

#2698 issue/2697 Added Backbone ES6 static property inheritance
  src/core/js/views/adaptView.js
  src/core/libraries/backbone.es6.js
  src/core/required/adapt/js/scriptLoader.js
Labels: bug, enhancement

#2708 issue/2669 Moved navigation handlers to navigationView, fixed buttons showing on first load
  src/core/js/router.js
  src/core/js/views/navigationView.js
  src/core/templates/nav.hbs
Labels: bug, enhancement
