Repository adaptlearning/adapt_framework, pull requests merged in 2020-08, with the labels that each got.

#2850 issue/2843 Corrected offset in scrolling container
  src/core/js/scrolling.js
Labels: bug

#2757 issue/2754-2755 Exposed Adapt.offlineStorage.save .serialize and .deserialize
  src/core/js/offlineStorage.js
Labels: enhancement, non-breaking

#2848 issue/2847 Improved notify subview handling
  src/core/js/notify.js
  src/core/js/views/notifyView.js
  src/core/less/core/notify.less
Labels: enhancement

#2862 issue/2861 Support umd underscorejs
  src/core/required/adapt/js/scriptLoader.js
Labels: bug, high priority

#2867 issue/2866 Added grunt compress task
  grunt/config/compress.js
  grunt/tasks/compress.js
  package.json
Labels: enhancement

#2806 issue/2805 Introduced optional component tracking ids
  grunt/helpers.js
  grunt/helpers/Data.js
  grunt/helpers/Framework.js
  grunt/helpers/Translate.js
  grunt/helpers/data/Language.js
  grunt/tasks/build.js
  grunt/tasks/dev.js
  grunt/tasks/diff.js
Labels: enhancement, non-breaking

#2857 issue/2853 Fixed csv delimiter detection on translate import
  grunt/helpers/Translate.js
  grunt/tasks/translate.js
Labels: bug, non-breaking

#2889 issue/2886 preventScroll fix now excludes firefox
  src/core/js/a11y.js
Labels: bug

#2885 issue/2884 Automatic detection of view-only question models
  src/core/js/adapt.js
  src/core/js/models/questionModel.js
Labels: bug
