Repository adaptlearning/adapt_framework, pull requests merged in 2020-07, with the labels that each got.

#2826 issues/2825 _isResetOnRevisit "false" string convertion
  src/core/js/views/questionView.js
Labels: bug

#2801 issue/2800 Enabled zoom on fixed position popup elements with scroll disabled
  src/core/js/a11y/scroll.js
Labels: bug

#2817 issue/2816 Remove fast-async to improve compilation time
  grunt/config/babel.js
  package.json
Labels: bug

#2759 issue/2758 Added deepClone API (v5.7.0)
  src/core/js/data.js
  src/core/js/models/adaptModel.js
  src/core/js/models/itemsQuestionModel.js
  src/core/js/models/questionModel.js
Labels: enhancement, non-breaking

#2748 issue/2747 Added questionModel attemptStates API
  src/core/js/models/adaptModel.js
  src/core/js/models/componentModel.js
  src/core/js/models/questionModel.js
  src/core/js/views/questionView.js
  src/course/config.json
Labels: enhancement, non-breaking

#2837 issue/2836 Added ability to exclude plugin(s) from 'production' build
  grunt/helpers.js
Labels: enhancement

#2852 issue/2851 Fixed DrawerView passing Backbone view to Adapt.a11y.focusFirst
  src/core/js/views/drawerView.js
Labels: bug

#2844 issue/2843 Fixed submit disabled on reset click
  src/core/js/models/questionModel.js
  src/core/js/views/questionView.js
Labels: bug

#2846 issue/2845 Presentation component save+restore
  src/core/js/models/componentModel.js
  src/core/js/models/itemsComponentModel.js
  src/core/js/models/questionModel.js
Labels: enhancement
