Repository adaptlearning/adapt_framework, pull requests merged in 2021-08, with the labels that each got.

#3212 issue/3211 Added preventScroll to reset click
  src/core/js/views/questionView.js
Labels: accessibility, bug

#3219 issue/3218
  src/core/js/data.js
  src/core/js/models/configModel.js
Labels: bug

#3221 Issue/3220
  src/core/js/data.js
Labels: bug

#3225 issue/3222-a Check available language names on lang search param
  grunt/helpers.js
  src/core/js/data.js
  src/core/js/models/configModel.js
Labels: bug, enhancement

#3230 Add support for authoring tool 1
  index.js
  package.json
  src/core/schema/article.schema.json
  src/core/schema/block.schema.json
  src/core/schema/component.schema.json
  src/core/schema/config.schema.json
  src/core/schema/content.schema.json
  src/core/schema/contentobject.schema.json
  src/core/schema/course.schema.json
Labels: enhancement

#3233 issue/3232 Fix for adapt-cli and adapt-contrib-core
  gitmodules.js
Labels: bug, high priority
