Repository adaptlearning/adapt_framework, pull requests merged in 2021-07, with the labels that each got.

#3185 issue/3184 Invalidate cache on missing files
  grunt/tasks/javascript.js
Labels: bug

#3189 issue/3188 Fix for compilation issues
  package.json
Labels: bug, high priority

#3194 issue/3195 Missing .model on line 465 creating error
  src/core/js/views/questionView.js
Labels: bug, high priority

#3209 issue/3208 Correct bad libraries/ imports
  grunt/config/javascript.js
  grunt/tasks/javascript.js
  package-lock.json
  package.json
Labels: bug, enhancement
