Repository adaptlearning/adapt_framework, pull requests merged in 2024-06, with the labels that each got.

#3567 Fix: Remove values for _feedback._altTitle in sample course (fixes #3566)
  src/course/en/components.json
Labels: enhancement

#3550 Fix: Default to secure connection for bower registry
  .bowerrc
Labels: bug

#3570 New: partly correct aria labels added to course _globals (fixes #3565)
  src/course/en/course.json
Labels: enhancement, accessibility
