Repository adaptlearning/adapt_framework, pull requests merged in 2025-04, with the labels that each got.

#3668 New: Add --capturedir and --rootdir to grunt migration tasks (fixes #3667)
  grunt/helpers.js
  grunt/helpers/Data.js
  grunt/helpers/Framework.js
  grunt/helpers/data/Language.js
  grunt/helpers/data/LanguageFile.js
  grunt/helpers/lib/JSONFile.js
  grunt/tasks/migration.js
Labels: enhancement

#3672 Fix: Path resolution to root in migrations scripts (fixes #3671)
  grunt/helpers/Framework.js
Labels: bug, high priority

#3676 Fix: ensure this.outputPath/sourcePath trailing slash isn't removed (fixes #3675)
  grunt/helpers/Framework.js
Labels: bug
